name: Deploy to EC2

on:
  push:
    branches:
      - deploy # deploy 브랜치에 푸시되면 워크플로우가 실행됩니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # GitHub Actions 러너를 설정합니다.

    steps:
    - uses: actions/checkout@v2 # 소스 코드를 체크아웃합니다.

    - name: Build React App
      run: |
        npm install
        npm run build

    - name: Copy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # EC2 호스트 이름
        username: ${{ secrets.EC2_USERNAME }} # EC2 사용자 이름
        key: ${{ secrets.EC2_SSH_KEY }} # EC2 SSH 키
        port: ${{ secrets.EC2_PORT }} # SSH 포트, 기본값은 22
        source: "build/, .env.local" # 빌드된 파일의 위치
        target: "/var/www/html" # EC2에서 애플리케이션을 호스팅할 위치

    # 필요한 경우 Nginx 재시작 등 추가 단계를 포함할 수 있습니다.
    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          sudo systemctl restart nginx
